### PR TITLE
Update to latest bevy main

### PR DESCRIPTION
**Pull request by rparrett**
Only the `basic` example needed updating, as far as I can tell, to support the new renderer / ui.

edit: And the `bevy_wgpu` feature no longer exists.

### CODE REVIEW

**Comment by NiklasEi** [comment]
Nice, thank you.
I got some tips on the Bevy Discord for unnecessary dependencies, so there are a few conflicts in the `Cargo.toml` file. But it should be easier now to manage the Bevy revisions.

**Review by NiklasEi — APPROVED** [review]

**Comment by rparrett** [comment]
Looks like CI failed on a stray `use bevy_utils::BoxedFuture;`. That's me on discord, btw.

**Comment by NiklasEi** [comment]
Yeah, I was just about to fix that. Do you want to?

Didn't know that, thanks for the tips!

**Comment by rparrett** [comment]
Nah, go for it.

**Comment by rparrett** [comment]
Or if you'd like, I can rebase

**Comment by NiklasEi** [comment]
I did the fixes, but it took a bit until I understood how to push them directly to a PR...

**Comment by rparrett** [comment]
Thanks!

**Pull request merged**
