### PR TITLE
Fixed builds for latest Bevy git commit

### PR DESCRIPTION
**Pull request by billyb2**
I just switched out AppBuilder for App, since it's a breaking change of the newest Bevy git.

### CODE REVIEW

**Comment by NiklasEi** [comment]
Thank you for the update! Could you base this PR on the `bevy_main` branch and keep the revision pinned? At the moment the diff contains a bit more.

**Comment by NiklasEi** [comment]
A heads-up that this plugin was just relicensed (see #16). This means that your contributions would be dual-licensed (see new note in the readme: https://github.com/NiklasEi/bevy_kira_audio/blob/main/README.md#contribution).

For completeness: maybe you could also comment in #16?

**Comment by billyb2** [comment]
> Thank you for the update! Could you base this PR on the `bevy_main` branch and keep the revision pinned? At the moment the diff contains a bit more.

Sorry, I don't know what keeping the revision pinned means.  Also, wouldn't it make more since to also include the 2 latest git commits, since they're two commits the bevy_main branch doesn't have.

**Comment by NiklasEi** [comment]
`bevy_main` currently pins the Bevy dependency at a specific revision using `rev` and the commit hash: https://github.com/NiklasEi/bevy_kira_audio/blob/bevy_main/Cargo.toml#L24-L25

I prefer this over simple depending on the latest main branch, because that means any update happens when I want it to happen.

The latest commits on `main` should also be on `bevy_main`.

**Comment by billyb2** [comment]
Ah alright, will do. I'll probably just make a new PR then

**Pull request closed without merging**
